# use_frameworks!

target 'AnalyticsObjcTestApp' do
  pod 'Analytics', :git => 'https://github.com/ButterflyNetwork/analytics-ios.git', :branch => 'podspec-dependencies'
  pod 'Segment-Mixpanel'
end



