#use_frameworks!

target 'AnalyticsObjcTestApp' do
  pod 'Analytics', :git => 'https://github.com/segmentio/analytics-ios.git', :branch => 'dev'
  pod 'Segment-GoogleAnalytics'
  pod 'Segment-Mixpanel'
end



