# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftRadio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftRadio
  pod 'Analytics', :path => './externals/analytics-ios'
  pod 'Segment-Mixpanel', '~> 1.3.0'

  target 'SwiftRadioUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
