# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Analytics'
  # Pods for Swift4

end
